api:
  name: "SalesDBSysAPI"
  version: "V1"
  host: "0.0.0.0"
  port: "8091"
  path: "/salesdbms/v1/*"
  console: "/salesdbms/v1/console/*"
  listener_timeout: "30000"
  id: "17797175"
  
db:
  host: "192.168.15.10"
  port: "1521"
  database: "XYZ"
  schema: "SALESDEV"
  user: "SALESDEV"
  password: "TestSALESDev1"
  maxPoolSize: "10"
  minPoolSize: "2"
  acquireIncrement: "2"
  maxWait: "10"
  cacheSize: "5"
  maxIdleTime: "60"
  queryTimeout: "10"
  table:
    salesOnline: "ORDERS_ONLINE"
    salesOffline: "ORDERS_OFFLINE"
    orderCommissions: "ORDER_COMMISSIONS"
    orderItems: "ORDER_ITEMS"